/** @type {import('tailwindcss').Config} */
module.exports = {
	content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
	safelist: [
		// Gallery color classes for dynamic usage
		'text-ew-orange',
		'text-ew-red',
		'text-ew-green',
		'text-ew-green-light',
		'border-ew-orange',
		'border-ew-red',
		'border-ew-green',
		'border-ew-green-light',
		'border-ew-orange/30',
		'border-ew-red/30',
		'border-ew-green/30',
		'border-ew-green-light/30',
		'bg-ew-orange',
		'bg-ew-red',
		'bg-ew-green',
		'bg-ew-green-light',
		'bg-ew-orange/20',
		'bg-ew-red/20',
		'bg-ew-green/20',
		'bg-ew-green-light/20',
		'bg-ew-orange/10',
		'bg-ew-red/10',
		'bg-ew-green/10',
		'border-ew-orange-light',
		'border-ew-red-light',
		'hover:border-ew-orange',
		'hover:border-ew-red',
		'hover:border-ew-green',
		'hover:bg-ew-orange',
		'hover:bg-ew-red',
		'hover:bg-ew-green',
		'hover:bg-ew-green-light',
		'hover:text-ew-orange',
		'hover:text-ew-red',
		'hover:text-ew-green',
		'bg-ew-orange/80',
		'bg-ew-red/80',
		'bg-ew-green/80',
		'group-hover:bg-ew-orange',
		'group-hover:bg-ew-red',
		'group-hover:bg-ew-green',
		'group-hover:text-ew-orange',
		'group-hover:text-ew-red',
		'group-hover:text-ew-green',
	],
	theme: {
		extend: {
			colors: {
				// Exit Wounds color palette
				'ew-orange': {
					DEFAULT: '#FF6B35',
					light: '#FF8C42',
					dark: '#FF4500',
				},
				'ew-red': {
					DEFAULT: '#D32F2F',
					light: '#FF5252',
					dark: '#B71C1C',
				},
				'ew-green': {
					DEFAULT: '#0D7377',
					light: '#14FFEC',
					dark: '#1A4D2E',
					forest: '#2C5F2D',
				},
				'ew-cream': '#F5F5DC',
			},
			fontFamily: {
				sans: ['Roboto', 'Inter var', 'Inter', 'system-ui', 'sans-serif'],
				khmer: ['Koulen', 'Roboto', 'Inter var', 'Inter', 'system-ui', 'sans-serif'],
			},
			animation: {
				'glitch': 'glitch 1s linear infinite',
				'glitch-skew': 'glitch-skew 2s ease-in-out infinite',
				'scan': 'scan 8s linear infinite',
			},
			keyframes: {
				glitch: {
					'0%, 100%': { transform: 'translate(0)' },
					'20%': { transform: 'translate(-2px, 2px)' },
					'40%': { transform: 'translate(-2px, -2px)' },
					'60%': { transform: 'translate(2px, 2px)' },
					'80%': { transform: 'translate(2px, -2px)' },
				},
				'glitch-skew': {
					'0%, 100%': { transform: 'skew(0deg)' },
					'10%': { transform: 'skew(-2deg)' },
					'20%': { transform: 'skew(2deg)' },
					'30%': { transform: 'skew(-2deg)' },
					'40%': { transform: 'skew(2deg)' },
					'50%': { transform: 'skew(0deg)' },
				},
				scan: {
					'0%, 100%': { transform: 'translateY(-100%)' },
					'50%': { transform: 'translateY(100%)' },
				},
			},
		},
	},
	plugins: [],
}
